version: '3'

services:
   db:
     image: posi
     networks:
        net: 
            ipv4_address: 172.18.0.2
     restart: always
     ports:
       - "5432:5432"

   python:
     depends_on:
       - db
     image: pythoni
     command: ifconfig
     networks:
        net: 
            ipv4_address: 172.18.0.3
     ports:
       - "5000:5000"
     restart: always
     volumes:
         - myvolume:/var/output
networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config: 
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
volumes:
  myvolume:
    external: true